# Generated by Django 4.0.3 on 2022-03-27 08:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import kufarbg_app.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_appuser_options_remove_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2), kufarbg_app.common.validators.validate_only_letters])),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2), kufarbg_app.common.validators.validate_only_letters])),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.Up to 15 digits is allowed", regex='^\\+?1?\\d{9, 15}$')])),
                ('age', models.DateField(blank=True, null=True, validators=[kufarbg_app.common.validators.MinDateValidator, kufarbg_app.common.validators.MaxDateValidator])),
                ('image', models.URLField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
