# Generated by Django 4.0.3 on 2022-03-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='image_url',
        ),
    ]
