# Generated by Django 4.0.2 on 2022-04-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_images_url', models.URLField()),
                ('good_thoughts', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='HomePagePhotos',
        ),
        migrations.DeleteModel(
            name='HomePageThoughts',
        ),
        migrations.AlterField(
            model_name='aboutusdata',
            name='site_owners_description',
            field=models.TextField(max_length=500),
        ),
    ]
