# Generated by Django 4.0.2 on 2022-04-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrips',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=250),
        ),
        migrations.DeleteModel(
            name='TripPhotos',
        ),
    ]
