# Generated by Django 4.0.2 on 2022-04-27 21:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_homepagedata_delete_homepagephotos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusdata',
            options={'verbose_name_plural': 'AboutUsData'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='destinations',
            options={'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='homepagedata',
            options={'verbose_name_plural': 'HomePageData'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='siteownerdata',
            options={'verbose_name_plural': 'SiteOwnerData'},
        ),
        migrations.AlterField(
            model_name='destinations',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
