# Generated by Django 4.0.2 on 2022-04-11 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_usertrips_photo_alter_comments_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, to='main_app.usertrips'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='user_comments',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
