# Generated by Django 4.0.2 on 2022-04-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comments_user_remove_comments_user_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
