# Generated by Django 4.0.2 on 2022-04-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_comments_user_comments_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='destination',
        ),
        migrations.AddField(
            model_name='comments',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.usertrips'),
            preserve_default=False,
        ),
    ]
