# Generated by Django 4.0.2 on 2022-04-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_comments_trip_comments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='comments',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.usertrips'),
            preserve_default=False,
        ),
    ]
